import { SymbolView, type AndroidSymbol, type SFSymbol, type SymbolViewProps } from 'expo-symbols';

// Android has no SF Symbols, so every symbol the app uses has its Material Symbol here. Anything missing from
// the list still shows a neutral dot instead of nothing.
const MATERIAL: Partial<Record<SFSymbol, AndroidSymbol>> = {
  'app.badge': 'app_badging',
  'arrow.triangle.2.circlepath': 'sync',
  'arrow.triangle.branch': 'call_split',
  'arrow.turn.up.left': 'turn_left',
  'arrow.turn.up.right': 'turn_right',
  'arrow.up': 'straight',
  'arrow.up.left': 'north_west',
  'arrow.up.right': 'north_east',
  'arrow.uturn.backward': 'undo',
  'arrow.uturn.down': 'u_turn_left',
  'bed.double': 'bed',
  bell: 'notifications',
  bicycle: 'directions_bike',
  'bolt.fill': 'bolt',
  'building.2': 'apartment',
  'building.columns': 'account_balance',
  bus: 'directions_bus',
  'bus.fill': 'directions_bus',
  calendar: 'calendar_month',
  'car.fill': 'directions_car',
  checkmark: 'check',
  'chevron.left': 'chevron_left',
  'chevron.right': 'chevron_right',
  'chevron.up.chevron.down': 'unfold_more',
  'clock.fill': 'schedule',
  'cross.case': 'medical_services',
  'doc.on.clipboard': 'content_paste',
  'door.left.hand.open': 'door_open',
  ellipsis: 'more_horiz',
  'ellipsis.circle': 'more_horiz',
  envelope: 'mail',
  'figure.run': 'directions_run',
  'figure.stairs': 'stairs',
  'figure.walk': 'directions_walk',
  'flag.checkered': 'flag',
  'fork.knife': 'restaurant',
  graduationcap: 'school',
  hammer: 'hardware',
  'hand.raised': 'front_hand',
  info: 'info',
  'iphone.slash': 'phonelink_erase',
  'list.number': 'format_list_numbered',
  location: 'my_location',
  'location.fill': 'my_location',
  'location.north.fill': 'navigation',
  'location.north.line.fill': 'navigation',
  lock: 'lock',
  magnifyingglass: 'search',
  map: 'map',
  'map.fill': 'map',
  'mappin.and.ellipse': 'pin_drop',
  'mappin.circle.fill': 'location_on',
  megaphone: 'campaign',
  number: 'tag',
  parkingsign: 'local_parking',
  pencil: 'edit',
  'person.2': 'group',
  'person.2.fill': 'group',
  'person.badge.plus': 'person_add',
  'person.crop.circle': 'account_circle',
  'person.crop.circle.fill': 'account_circle',
  plus: 'add',
  'point.3.connected.trianglepath.dotted': 'hub',
  'rectangle.portrait.and.arrow.right': 'logout',
  'rectangle.stack': 'web_stories',
  safari: 'explore',
  scope: 'my_location',
  'speaker.slash.fill': 'volume_off',
  'speaker.wave.2': 'volume_up',
  'speaker.wave.2.fill': 'volume_up',
  'square.and.arrow.up': 'share',
  trash: 'delete',
  'view.2d': 'map',
  'view.3d': 'view_in_ar',
  'wrench.and.screwdriver': 'build',
  xmark: 'close',
};

type IconProps = Omit<SymbolViewProps, 'name'> & { name: SFSymbol };

/** An SF Symbol on iOS and the matching Material Symbol on Android. */
export function Icon({ name, ...props }: IconProps) {
  return <SymbolView name={{ ios: name, android: MATERIAL[name] ?? 'circle' }} {...props} />;
}
